### ISSUE TITLE
Libros de IVA y archivos Iva Digital .txt

### ISSUE THREAD

**Issue by wgtoneatto** [OdooAR/odoo-argentina-doc#18]
Hola Ignacio, buen día, estoy trabajando con odoo 15 en ubuntu 20.04 lts, con localización argentina codize, lo que sucede es que al generar los libros de iva, si no hay movimientos, los genera, tanto el .pdf como .xlsx, pero al generarlos con movimientos me da el siguiente error al imprimir .pdf: 
"RPC_ERROR

Arbitrary Uncaught Python Exception

500
Internal Server Error
                                    The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

y al imprimir .xlsx:
"RPC_ERROR

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo15/sources/report_xlsx/controllers/main.py", line 63, in report_download
    response = self.report_routes(
  File "/opt/odoo15/odoo15/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/sources/report_xlsx/controllers/main.py", line 37, in report_routes
    xlsx = report.with_context(**context)._render_xlsx(docids, data=data)[0]
  File "/opt/odoo15/sources/report_xlsx/models/ir_report.py", line 22, in _render_xlsx
    report_model.with_context(active_model=self.model)
  File "/opt/odoo15/sources/report_xlsx/report/report_abstract_xlsx.py", line 98, in create_xlsx_report
    self.generate_xlsx_report(workbook, data, objs)
  File "/opt/odoo15/sources/odoo-argentina-codize/l10n_ar_ledger/account_vat_report_xlsx.py", line 46, in generate_xlsx_report
    taxes = json.loads(self.tax_totals_json)['groups_by_subtotal']['Importe libre de impuestos']
AttributeError: 'report.l10n_ar_ledger.account_vat_ledger_xlsx' object has no attribute 'tax_totals_json' "

que puede estar pasando?

**Comment by ibuioli** [comment]
No sé si este issue tendría que estar acá, debería estar en el propio repo de la localización. Pero por lo que veo es un error en el código, Lo vamos a corregir pero está atento a la actualización por el repo.

**Comment by wgtoneatto** [comment]
Gracias Ignacio, si tenes razon, lo deberia haber puesto en la localizacion

**Comment by wgtoneatto** [comment]
Hola Ignacio, prove la actualización y me da este error:

Traceback (most recent call last):
  File "/opt/odoo15/sources/report_xlsx/controllers/main.py", line 63,
in report_download
    response = self.report_routes(
  File "/opt/odoo15/odoo15/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/sources/report_xlsx/controllers/main.py", line 37,
in report_routes
    xlsx = report.with_context(**context)._render_xlsx(docids, data=data)[0]
  File "/opt/odoo15/sources/report_xlsx/models/ir_report.py", line 22,
in _render_xlsx
    report_model.with_context(active_model=self.model)
  File "/opt/odoo15/sources/report_xlsx/report/report_abstract_xlsx.py",
line 98, in create_xlsx_report
    self.generate_xlsx_report(workbook, data, objs)
  File "/opt/odoo15/sources/odoo-argentina-codize/l10n_ar_ledger/account_vat_report_xlsx.py",
line 46, in generate_xlsx_report
    taxes = json.loads(obj.tax_totals_json)['groups_by_subtotal']['Importe
libre de impuestos']
AttributeError: 'report.l10n_ar_ledger.account_vat_ledger_xlsx' object
has no attribute 'tax_totals_json'
